version: '3'

services:
  app:
    image: app
    ports:
    - 8080:8080
    environment:
    - ACCESS_TOKEN=${E2E_ACCESS_TOKEN}
    - RABBIT_QUEUE_TTL=5000
    - CLOCKS_PURGE_INTERVAL=4000
    - SCHEDULES_PURGE_INTERVAL=250
    - TICKS_PURGE_INTERVAL=500
    - TICKS_PURGE_KEEPCOUNT=1
