version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
    - 9999:15672
    - 5673:5672

  mongo:
    image: mongo:3.6
    ports:
    - 27018:27017

  app:
    build: ..
    ports:
      - 8081:8080
    environment:
      - RABBIT_URI=amqp://rabbit
      - MONGO_URI=mongodb://mongo/e2e-test
      - SELF_DOMAIN=http://localhost:8081
      - ACCESS_TOKEN=a5f98e2b068ee51f90fd81c530e7fb4e306e7f42
    volumes:
      - "./application.yml:/opt/app/config/application.yml"
    depends_on:
      - rabbit
      - mongo

